#+TITLE: Epic -- Evernote Picker for Cocoa Emacs
#+AUTHOR: Yoshinari Nomura (乃村 能成)
#+EMAIL: nom@quickhack.net

[[http://melpa.org/#/epic][file:http://melpa.org/packages/epic-badge.svg]]

* What is Epic?

  Epic is a small elisp to access Evernote process via AppleScript.
  Epic has these functions:

  - Completing read for tags and notebooks:
    + ``epic-read-notebook'', ``epic-read-tag'', ``epic-read-tag-list'' ::
      for the completion of tags and notebooks.

  - Creation of note articles:
    + ``epic-create-note-from-region'', ``epic-create-note-from-file'' ::
      for creation of a new note in your Evernote.app.

  - For Org-mode users:
    + ``epic-create-note-from-org-buffer'' ::
      Export current org buffer into a note of Evernote in the form of HTML.
      The original org buffer is also attached to the exported note.
      Epic inserts the link string in the org buffer to keep the
      correspondence with the previously exported note.
      The Link is looks like:

        : #+EPIC_LINK: evernote:///view/123456/s1/xxxxxxxx-xxxx-.../

      Using this link, epic will export to the same note as before
      (nullify the previously exported note and re-export into it).

    + ``epic-insert-selected-note-as-org-links'' ::
      Capture selected notes in Evernote and insert org-style links.

    + Org-mode becomes to recognize evernote:// links
      C-cC-o (org-open-at-point) works on evernote:// links

  - For helm users:
    Add some helm-friendly functions and settings:
    + epic-helm
    + helm-c-source-evernote-tags
    + helm-c-source-evernote-notebooks
    + helm-c-source-evernote-notebooks-in-stack

  - For Mew users:
    + ``epic-mew-forward-to-evernote'' ::
       Nifty mail forwarder.
       You need to set the vars: ``epic-evernote-mail-address'',
       ``epic-evernote-mail-headers''

    + ``epic-mew-create-note'' ::
       Import a mail article into the local Evernote.app.

* Setting Example

  : (require 'epic)
  : (define-key global-map [(control ?:)] 'epic-helm)
  : (define-key mew-summary-mode-map "r" 'epic-mew-create-note)
  : (define-key mew-summary-mode-map "e" 'epic-mew-forward-to-evernote)
  : (setq epic-evernote-mail-address "??????@???.evernote.com")

* Contact Info
  The updated version might be available from:
  http://github.com/yoshinari-nomura/epic
